// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamAxis.Api.Data;

#nullable disable

namespace StreamAxis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AddEpisodesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("StreamAxis.Api.Entities.Content", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Contents");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Episode", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ContentId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<int>("EpisodeNumber")
                    .HasColumnType("INTEGER");

                b.Property<int>("SeasonNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("StreamUrl")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("PosterUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ContentId");

                b.ToTable("Episodes");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Episode", b =>
            {
                b.HasOne("StreamAxis.Api.Entities.Content", "Content")
                    .WithMany()
                    .HasForeignKey("ContentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
