// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamAxis.Api.Data;

#nullable disable

namespace StreamAxis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223023716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("StreamAxis.Api.Entities.AppConfig", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CurrentVersion")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsUpdateRequired")
                    .HasColumnType("BOOLEAN");

                b.Property<string>("LatestApkUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("UpdateMessage")
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("AppConfigs");

                b.HasData(
                    new
                    {
                        Id = 1,
                        CurrentVersion = "1.0",
                        IsUpdateRequired = false,
                        UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    });
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Content", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Category")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("BOOLEAN");

                b.Property<string>("PosterUrl")
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("StreamUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("Contents");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Category = 1,
                        CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Demo stream",
                        IsActive = true,
                        PosterUrl = "https://peach.blender.org/wp-content/uploads/title_anouncement.jpg",
                        StreamUrl = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
                        Title = "Big Buck Bunny",
                        UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 2,
                        Category = 1,
                        CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "Demo stream",
                        IsActive = true,
                        PosterUrl = "https://mango.blender.org/wp-content/uploads/tearsofsteel_thumbnail.jpg",
                        StreamUrl = "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
                        Title = "Tears of Steel",
                        UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 3,
                        Category = 0,
                        CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Description = "24/7 demo channel",
                        IsActive = true,
                        StreamUrl = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
                        Title = "Live TV Demo",
                        UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    });
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Device", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("LastLoginDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("UserId", "DeviceId")
                    .IsUnique();

                b.ToTable("Devices");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Session", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Token")
                    .IsUnique();

                b.HasIndex("UserId");

                b.ToTable("Sessions");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("ExpirationDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsActive")
                    .HasColumnType("BOOLEAN");

                b.Property<int>("MaxDevices")
                    .HasColumnType("INTEGER");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Users");

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        ExpirationDate = new DateTime(2035, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        MaxDevices = 10,
                        Password = "admin",
                        UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Username = "admin"
                    },
                    new
                    {
                        Id = 2,
                        CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        ExpirationDate = new DateTime(2025, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                        IsActive = true,
                        MaxDevices = 1,
                        Password = "demo",
                        UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        Username = "demo"
                    });
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.UserPlaybackState", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ContentId")
                    .HasColumnType("INTEGER");

                b.Property<long>("LastPositionTicks")
                    .HasColumnType("BIGINT");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ContentId");

                b.HasIndex("UserId", "ContentId")
                    .IsUnique();

                b.ToTable("UserPlaybackStates");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Device", b =>
            {
                b.HasOne("StreamAxis.Api.Entities.User", "User")
                    .WithMany("Devices")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Session", b =>
            {
                b.HasOne("StreamAxis.Api.Entities.User", "User")
                    .WithMany("Sessions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.UserPlaybackState", b =>
            {
                b.HasOne("StreamAxis.Api.Entities.Content", "Content")
                    .WithMany("UserPlaybackStates")
                    .HasForeignKey("ContentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("StreamAxis.Api.Entities.User", "User")
                    .WithMany("PlaybackStates")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Content");
                b.Navigation("User");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.Content", b =>
            {
                b.Navigation("UserPlaybackStates");
            });

            modelBuilder.Entity("StreamAxis.Api.Entities.User", b =>
            {
                b.Navigation("Devices");
                b.Navigation("PlaybackStates");
                b.Navigation("Sessions");
            });
#pragma warning restore 612, 618
        }
    }
}
